baseURL = "http://davidomar.com/"
languageCode = "en-us"
title = "i'm david"
theme = "hugo-journal"

[params]
  description = "i'm a developer and artist. i maintain a blog about generative art. i write some ideas about software or life. lowercase is intentional"
  githubUsername = "davidomarf"
  twitterUsername = "davidomarf"
  tagline = """
  [github](https://github.com/davidomarf) &nbsp; • &nbsp; 
  [resume](/resume.pdf) &nbsp; • &nbsp;
  [writings](#writings) &nbsp; • &nbsp;
  [projects](#projects) &nbsp; • &nbsp;
  [talks](#talks)
  """
  resume = "./resume.pdf"
  gtag = "UA-115039725-1"
[params.work]
  jobTitle = "Author"
  company = "Generative Mistakes"
  companyUrl = "https://gen.davidomar.com/"
[params.gpg]
  key = "0x9E07A0FB801E18A9"
  fingerprint = "E069 59EE 0FFA 5971 6569 436A 9E07 A0FB 801E 18A9"
  link = "https://pgp.mit.edu/pks/lookup?op=get&search=0x9E07A0FB801E18A9"
[author]
  name = "David Omar"
[blackfriday]
  plainIDAnchors=true
  hrefTargetBlank=true